### ISSUE TITLE
'Bugzilla' triggers the rule

### ISSUE THREAD

**Issue by berezovskyi** [ahmadassaf/code-notes#1]
Was used in a comment like `//Bugzilla #####`. Looks like this:

![image](https://cloud.githubusercontent.com/assets/64734/23385063/faa1a616-fd4d-11e6-91a0-a03270dc3fea.png)

😄

**Comment by ahmadassaf** [comment]
@berezovskyi fixed in 1.0.3 :) thanks for the feedback

Basically now after each keyword you must have a colon so that `BUG:` will be caught and not just `BUG*`
