### ISSUE TITLE
node_modules directory

### ISSUE THREAD

**Issue by mainrs** [ahmadassaf/code-notes#2]
Just stumbled across your library. Is there a reason why you include the node_modules directory within the repo? Generally speaking, the directory can always be generated by the underlying system, there is no real need to do so. I can create a PR to remove it from the repo if no one has anything against it. :smile:

**Comment by ahmadassaf** [comment]
@SirWindfield oops ! thanks a lot for spotting that .. just fixed that :) thanks a lot for spotting it

**Comment by mainrs** [comment]
No problem :smile:
